# Generated by Django 4.2.3 on 2023-08-04 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('dietid', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('threemeals', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=9)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('threemeals', 'created', 'userid')},
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dishid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('hits', models.IntegerField()),
                ('detail', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('식품상세분류', '식품상세분류'), ('해조류', '해조류'), ('채소류', '채소류'), ('차류', '차류'), ('주류', '주류'), ('조미료류', '조미료류'), ('조리가공품류', '조리가공품류'), ('음료류', '음료류'), ('육류', '육류'), ('유지류', '유지류'), ('우유 및 유제품류', '우유 및 유제품류'), ('어패류 및 기타 수산물', '어패류 및 기타 수산물'), ('버섯류', '버섯류'), ('두류', '두류'), ('당류', '당류'), ('난류', '난류'), ('기타', '기타'), ('과실류', '과실류'), ('곡류 및 그 제품', '곡류 및 그 제품'), ('견과류 및 종실류', '견과류 및 종실류'), ('감자 및 전분류', '감자 및 전분류')], max_length=12)),
                ('energy', models.FloatField()),
                ('moisture', models.FloatField()),
                ('protein', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('natrium', models.FloatField()),
            ],
            options={
                'ordering': ['no'],
            },
        ),
        migrations.CreateModel(
            name='DishDetail',
            fields=[
                ('dishdetailid', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('dishid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishdetail', to='food.dish')),
                ('foodno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishdetail', to='food.food')),
            ],
        ),
        migrations.CreateModel(
            name='DietDetail',
            fields=[
                ('dietdetailid', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('dietid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietdetail', to='food.diet')),
                ('dishid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietdetail', to='food.dish')),
                ('foodno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietdetail', to='food.food')),
            ],
        ),
    ]
